Setup:
    grasp_path: "/vols/cms/lcr119/MCProduction/GrASP/2024Background/data/GrASP_Run3Winter24xGS.csv"
    target_dir: "/vols/cms/lcr119/MCProduction/GrASP/2024Background/targets"
    campaign: "2024Background"
